// This is an autogenerated file from Firebase Studio.

'use server';
/**
 * @fileOverview A flow that generates sentences from keywords.
 *
 * - generateSentenceFromKeywords - A function that generates a sentence from keywords.
 * - GenerateSentenceFromKeywordsInput - The input type for the generateSentenceFromKeywords function.
 * - GenerateSentenceFromKeywordsOutput - The return type for the generateSentenceFromKeywords function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const GenerateSentenceFromKeywordsInputSchema = z.object({
  keywords: z
    .string()
    .describe('The keywords to include in the sentence.')
    .min(1),
  styleGuide: z
    .string()
    .optional()
    .describe('A guide for writing style, tone and manner.'),
});
export type GenerateSentenceFromKeywordsInput = z.infer<
  typeof GenerateSentenceFromKeywordsInputSchema
>;

const GenerateSentenceFromKeywordsOutputSchema = z.object({
  sentence: z.string().describe('The generated sentence.'),
});
export type GenerateSentenceFromKeywordsOutput = z.infer<
  typeof GenerateSentenceFromKeywordsOutputSchema
>;

export async function generateSentenceFromKeywords(
  input: GenerateSentenceFromKeywordsInput
): Promise<GenerateSentenceFromKeywordsOutput> {
  return generateSentenceFromKeywordsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateSentenceFromKeywordsPrompt',
  input: {
    schema: z.object({
      keywords: z
        .string()
        .describe('The keywords to include in the sentence.')
        .min(1),
      styleGuide: z
        .string()
        .optional()
        .describe('A guide for writing style, tone and manner.'),
    }),
  },
  output: {
    schema: z.object({
      sentence: z.string().describe('The generated sentence.'),
    }),
  },
  prompt: `You are an expert copywriter. You will generate a sentence that naturally incorporates the given keywords. The sentence should be engaging and relevant to the context of sponsored posts and ads.

Keywords: {{{keywords}}}

{{#if styleGuide}}
Style Guide: {{{styleGuide}}}
{{/if}}

Sentence:`,
});

const generateSentenceFromKeywordsFlow = ai.defineFlow<
  typeof GenerateSentenceFromKeywordsInputSchema,
  typeof GenerateSentenceFromKeywordsOutputSchema
>({
  name: 'generateSentenceFromKeywordsFlow',
  inputSchema: GenerateSentenceFromKeywordsInputSchema,
  outputSchema: GenerateSentenceFromKeywordsOutputSchema,
},
async input => {
  const {output} = await prompt(input);
  return output!;
});
